---
- name: Admiral Stats に必要な gem のインストール
  command: /bin/bash -l -c "bundle install"
  args:
    chdir: /vagrant

- name: 開発用データベースの作成
  command: mysql -uroot -e'CREATE DATABASE admiral_stats_development CHARACTER SET utf8;'

- name: 開発用テーブルの作成
  command: /bin/bash -l -c "rails db:migrate"
  args:
    chdir: /vagrant

- name: 開発用テーブルへの初期データ登録
  command: /bin/bash -l -c "rails console < db/seeds.rb"
  args:
    chdir: /vagrant

- name: テスト用データベースの作成
  command: mysql -uroot -e'CREATE DATABASE admiral_stats_test CHARACTER SET utf8;'

- name: テスト用テーブルの作成
  command: /bin/bash -l -c "RAILS_ENV=test rails db:migrate"
  args:
    chdir: /vagrant
